import { REGIONS, type Region } from "./regions"

export interface TaxonCharacters {
  habit: string[]
  arrangement?: string[]
  leafType?: string[]
  shape?: string[]
  margin?: string[]
  venation?: string[]
  texture?: string[]
  petiole?: string[]
  lobes?: string[]
  fascicle?: string[]
  bark?: string[]
  exudate?: string[]
  buds?: string[]
  roots?: string[]
  reproductive?: string[]
  fruit?: string[]
  scent?: string[]
  site?: string[]
}

export type NameKind = "species" | "hybrid" | "aggregate"

export interface Taxon {
  id: string
  scientificName: string
  nameKind?: NameKind
  commonNames: string[]
  family: string
  nativeRegions: Region[]
  plantedRegions: Region[]
  rangeText: string
  summary: string
  traits: string[]
  woodyNote?: string
  toxic?: string
  invasive?: string
  similarTo: string[]
  characters: TaxonCharacters
}

const ALL_REGIONS: Region[] = REGIONS.map((region) => region.id)

function elsewhere(native: Region[]): Region[] {
  return ALL_REGIONS.filter((region) => !native.includes(region))
}

export const TAXA: Taxon[] = [
  {
    id: "quercus-robur",
    scientificName: "Quercus robur",
    commonNames: ["English oak", "pedunculate oak"],
    family: "Fagaceae",
    nativeRegions: ["europe", "west-asia"],
    plantedRegions: ["north-america", "oceania", "east-asia", "south-america"],
    rangeText: "Native across much of Europe into western Asia. Widely planted in parks.",
    summary:
      "A park and woodland oak. Leaves sit on a very short stalk and the base often has a small ear. Acorns hang on a long stalk.",
    traits: ["Short petiole", "Rounded lobes", "Acorns on a long stalk", "Fissured bark"],
    woodyNote: "Buds cluster at the shoot tip. Old bark is deeply fissured.",
    similarTo: ["quercus-alba", "platanus-acerifolia"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lobed-pinnate"],
      margin: ["entire"],
      venation: ["pinnate"],
      texture: ["smooth"],
      petiole: ["short"],
      lobes: ["many"],
      bark: ["fissured"],
      exudate: ["none"],
      buds: ["clustered"],
      reproductive: ["catkin"],
      fruit: ["acorn"],
      scent: ["none"],
      site: ["forest", "open", "street"],
    },
  },
  {
    id: "quercus-alba",
    scientificName: "Quercus alba",
    commonNames: ["white oak"],
    family: "Fagaceae",
    nativeRegions: ["north-america"],
    plantedRegions: ["europe"],
    rangeText: "Native to eastern North America.",
    summary:
      "An eastern North American oak with rounded lobes and a longer leaf stalk than English oak. Bark on older trees is pale and scaly.",
    traits: ["Longer petiole than English oak", "Rounded lobes", "Pale scaly bark"],
    woodyNote: "Buds cluster at the tip, as in other oaks.",
    similarTo: ["quercus-robur"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lobed-pinnate"],
      margin: ["entire"],
      venation: ["pinnate"],
      texture: ["smooth"],
      petiole: ["long"],
      lobes: ["many"],
      bark: ["scaly"],
      exudate: ["none"],
      buds: ["clustered"],
      reproductive: ["catkin"],
      fruit: ["acorn"],
      scent: ["none"],
      site: ["forest", "open"],
    },
  },
  {
    id: "acer-saccharum",
    scientificName: "Acer saccharum",
    commonNames: ["sugar maple"],
    family: "Sapindaceae",
    nativeRegions: ["north-america"],
    plantedRegions: ["europe"],
    rangeText: "Native to eastern North America.",
    summary:
      "Opposite leaves with about five shallow lobes and a few coarse teeth. Fruits are paired winged keys. Old bark furrows.",
    traits: ["Opposite leaves", "Five shallow lobes", "Paired samaras"],
    similarTo: ["acer-palmatum", "platanus-acerifolia", "liquidambar-styraciflua"],
    characters: {
      habit: ["tree"],
      arrangement: ["opposite"],
      leafType: ["simple"],
      shape: ["lobed-palmate"],
      margin: ["toothed"],
      venation: ["palmate"],
      texture: ["smooth"],
      petiole: ["long"],
      lobes: ["five"],
      bark: ["fissured"],
      exudate: ["none"],
      buds: ["small-dry"],
      reproductive: ["tiny"],
      fruit: ["samara"],
      scent: ["none"],
      site: ["forest", "open", "street"],
    },
  },
  {
    id: "acer-palmatum",
    scientificName: "Acer palmatum",
    commonNames: ["Japanese maple"],
    family: "Sapindaceae",
    nativeRegions: ["east-asia"],
    plantedRegions: elsewhere(["east-asia"]),
    rangeText: "Native to Japan, Korea and nearby China. Planted in gardens worldwide.",
    summary:
      "A small maple with opposite leaves cut into deep, pointed lobes. Bark stays fairly smooth. Fruits are small paired keys.",
    traits: ["Opposite leaves", "Deep pointed lobes", "Small tree", "Smooth bark"],
    similarTo: ["acer-saccharum"],
    characters: {
      habit: ["tree", "shrub"],
      arrangement: ["opposite"],
      leafType: ["simple"],
      shape: ["lobed-palmate"],
      margin: ["toothed"],
      venation: ["palmate"],
      texture: ["smooth"],
      petiole: ["long"],
      lobes: ["many"],
      bark: ["smooth"],
      exudate: ["none"],
      buds: ["small-dry"],
      reproductive: ["tiny"],
      fruit: ["samara"],
      scent: ["none"],
      site: ["street", "open"],
    },
  },
  {
    id: "platanus-acerifolia",
    scientificName: "Platanus × hispanica",
    nameKind: "hybrid",
    commonNames: ["London plane"],
    family: "Platanaceae",
    nativeRegions: [],
    plantedRegions: [
      "europe",
      "north-america",
      "west-asia",
      "central-america",
      "east-asia",
      "oceania",
      "south-america",
      "africa",
      "south-asia",
    ],
    rangeText:
      "A planted hybrid of American and oriental planes, with no wild native range. A standard street tree in temperate cities.",
    summary:
      "A planted hybrid, not a wild species. POWO accepts Platanus × hispanica. Older books call the same tree Platanus × acerifolia. Maple-like leaves, but they are alternate, not opposite. Bark peels in cream, olive and brown patches. Fruits are round balls on stalks.",
    traits: ["Alternate lobed leaves", "Camouflage peeling bark", "Round fruit balls"],
    woodyNote: "The petiole base hides next year's bud.",
    similarTo: ["acer-saccharum", "liquidambar-styraciflua"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lobed-palmate"],
      margin: ["toothed"],
      venation: ["palmate"],
      texture: ["smooth"],
      petiole: ["long"],
      lobes: ["five", "three"],
      bark: ["peeling"],
      exudate: ["none"],
      reproductive: ["tiny"],
      fruit: ["round-ball"],
      scent: ["none"],
      site: ["street", "open"],
    },
  },
  {
    id: "liquidambar-styraciflua",
    scientificName: "Liquidambar styraciflua",
    commonNames: ["American sweetgum"],
    family: "Altingiaceae",
    nativeRegions: ["north-america", "central-america"],
    plantedRegions: ["europe", "south-america", "oceania", "east-asia"],
    rangeText: "Native from the eastern United States through Central America. Often planted as a street tree.",
    summary:
      "Star-shaped alternate leaves, usually with five lobes and fine teeth. Broken twigs can smell resinous. The fruit is a spiky ball.",
    traits: ["Alternate star leaves", "Five lobes", "Spiky balls", "Resin"],
    similarTo: ["liquidambar-formosana", "platanus-acerifolia", "acer-saccharum"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lobed-palmate"],
      margin: ["toothed"],
      venation: ["palmate"],
      texture: ["glossy"],
      petiole: ["long"],
      lobes: ["five"],
      bark: ["fissured"],
      exudate: ["resin"],
      reproductive: ["tiny"],
      fruit: ["spiky-ball"],
      scent: ["aromatic"],
      site: ["forest", "open", "street"],
    },
  },
  {
    id: "liquidambar-formosana",
    scientificName: "Liquidambar formosana",
    commonNames: ["Formosan sweetgum", "Taiwan sweetgum"],
    family: "Altingiaceae",
    nativeRegions: ["east-asia"],
    plantedRegions: ["southeast-asia"],
    rangeText: "Native to Taiwan, southern China and Vietnam.",
    summary:
      "The sweetgum of Taiwan and nearby forests. Leaves are usually three-lobed rather than five. Fruits are spiky balls, and the twigs are resinous.",
    traits: ["Usually three lobes", "Spiky balls", "Resinous twigs"],
    woodyNote: "A Taiwan and south China forest tree, also planted.",
    similarTo: ["liquidambar-styraciflua"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lobed-palmate"],
      margin: ["toothed"],
      venation: ["palmate"],
      texture: ["glossy"],
      petiole: ["long"],
      lobes: ["three"],
      bark: ["fissured"],
      exudate: ["resin"],
      reproductive: ["tiny"],
      fruit: ["spiky-ball"],
      scent: ["aromatic"],
      site: ["forest", "open"],
    },
  },
  {
    id: "betula-pendula",
    scientificName: "Betula pendula",
    commonNames: ["silver birch"],
    family: "Betulaceae",
    nativeRegions: ["europe", "west-asia"],
    plantedRegions: ["north-america", "oceania"],
    rangeText: "Native across Europe into western Asia. Planted elsewhere as an ornamental.",
    summary:
      "White bark that peels in thin strips, with black fissures lower down. Leaves are small, triangular and sharply toothed. Shoots often droop.",
    traits: ["White peeling bark", "Small toothed leaves", "Catkins"],
    woodyNote: "Young twigs are slender and often hanging.",
    similarTo: ["populus-tremuloides"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["ovate"],
      margin: ["toothed"],
      venation: ["pinnate"],
      texture: ["smooth"],
      petiole: ["long"],
      lobes: ["none"],
      bark: ["peeling"],
      exudate: ["none"],
      reproductive: ["catkin"],
      fruit: ["small-winged"],
      scent: ["none"],
      site: ["forest", "open", "street"],
    },
  },
  {
    id: "fagus-sylvatica",
    scientificName: "Fagus sylvatica",
    commonNames: ["European beech"],
    family: "Fagaceae",
    nativeRegions: ["europe"],
    plantedRegions: ["north-america", "oceania"],
    rangeText: "Native to Europe. Planted in parks and shelter belts.",
    summary:
      "Smooth gray bark and elliptic leaves with a wavy edge and straight side veins. Buds are long and pointed. Nuts sit in a bristly husk.",
    traits: ["Smooth gray bark", "Wavy entire-looking margin", "Long pointed buds"],
    woodyNote: "The long pointed buds are the winter mark.",
    similarTo: ["nothofagus-grandis"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["elliptic"],
      margin: ["wavy", "entire"],
      venation: ["pinnate"],
      texture: ["smooth"],
      petiole: ["short"],
      lobes: ["none"],
      bark: ["smooth"],
      exudate: ["none"],
      buds: ["long-pointed"],
      reproductive: ["catkin"],
      fruit: ["nut-in-husk"],
      scent: ["none"],
      site: ["forest", "open", "street"],
    },
  },
  {
    id: "ginkgo-biloba",
    scientificName: "Ginkgo biloba",
    commonNames: ["ginkgo", "maidenhair tree"],
    family: "Ginkgoaceae",
    nativeRegions: ["east-asia"],
    plantedRegions: elsewhere(["east-asia"]),
    rangeText: "Native to China. Planted on streets in temperate cities worldwide.",
    summary:
      "Fan-shaped leaves with forking veins, often with a notch at the tip. The fleshy seed smells foul. The leaves do not.",
    traits: ["Fan leaf", "Forking veins", "Foul seed, not foul leaves"],
    toxic: "The seed is poisonous in quantity, and the fleshy coat irritates skin. Do not taste it.",
    woodyNote: "Leaves are clustered on short shoots. Old trunks furrow.",
    similarTo: [],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["fan"],
      margin: ["entire"],
      venation: ["dichotomous"],
      texture: ["smooth"],
      petiole: ["long"],
      lobes: ["none"],
      bark: ["fissured"],
      exudate: ["none"],
      reproductive: ["tiny"],
      fruit: ["fleshy-seed"],
      scent: ["none", "foul"],
      site: ["street", "open"],
    },
  },
  {
    id: "pinus-sylvestris",
    scientificName: "Pinus sylvestris",
    commonNames: ["Scots pine"],
    family: "Pinaceae",
    nativeRegions: ["europe", "west-asia"],
    plantedRegions: ["north-america", "oceania"],
    rangeText: "Native from western Europe across northern Eurasia.",
    summary:
      "Needles in pairs, often twisted and blue-green. Bark on the upper trunk flakes orange. Cones are woody and small.",
    traits: ["Two needles per bundle", "Orange flaky upper bark", "Woody cones"],
    woodyNote: "Buds sit clustered at the shoot tip. Broken bark is resinous.",
    similarTo: ["pinus-radiata", "casuarina-equisetifolia"],
    characters: {
      habit: ["tree"],
      leafType: ["needle"],
      shape: ["linear"],
      margin: ["entire"],
      fascicle: ["two"],
      bark: ["scaly"],
      exudate: ["resin"],
      buds: ["clustered"],
      reproductive: ["cone"],
      fruit: ["cone"],
      scent: ["aromatic"],
      lobes: ["none"],
      site: ["forest", "open"],
    },
  },
  {
    id: "pinus-radiata",
    scientificName: "Pinus radiata",
    commonNames: ["Monterey pine", "radiata pine"],
    family: "Pinaceae",
    nativeRegions: ["north-america"],
    plantedRegions: ["oceania", "south-america", "africa", "europe", "south-asia"],
    rangeText: "Native to a small stretch of coastal California. Planted in huge stands in the southern hemisphere.",
    summary:
      "Needles usually in threes, longer than Scots pine. Bark is dark and furrowed rather than orange. A common plantation pine.",
    traits: ["Usually three needles", "Dark furrowed bark", "Plantation tree"],
    invasive:
      "It invades fynbos and some Australian bush outside the plantation. Do not spread seed on a hunch.",
    similarTo: ["pinus-sylvestris"],
    characters: {
      habit: ["tree"],
      leafType: ["needle"],
      shape: ["linear"],
      margin: ["entire"],
      fascicle: ["three"],
      bark: ["fissured"],
      exudate: ["resin"],
      buds: ["clustered"],
      reproductive: ["cone"],
      fruit: ["cone"],
      scent: ["aromatic"],
      lobes: ["none"],
      site: ["forest", "open"],
    },
  },
  {
    id: "taxus-baccata",
    scientificName: "Taxus baccata",
    commonNames: ["European yew"],
    family: "Taxaceae",
    nativeRegions: ["europe", "west-asia", "africa"],
    plantedRegions: ["north-america", "oceania", "east-asia"],
    rangeText: "Native to Europe, the Atlas Mountains and western Asia. A common churchyard and hedge tree.",
    summary:
      "Flat sprays of dark needles, not bundled like a pine. The seed sits in a red fleshy cup. There is no woody cone.",
    traits: ["Flat needle sprays", "Red cup, not a cone", "Flaky bark"],
    toxic:
      "Yew is poisonous in the needles, bark and seed. The red flesh is the only part that is not poisonous, and the seed inside it is. Do not put any of it in your mouth.",
    similarTo: ["pinus-sylvestris"],
    characters: {
      habit: ["tree", "shrub"],
      arrangement: ["alternate"],
      leafType: ["needle"],
      shape: ["linear"],
      margin: ["entire"],
      fascicle: ["flat-spray"],
      texture: ["glossy"],
      bark: ["scaly"],
      exudate: ["none"],
      reproductive: ["tiny"],
      fruit: ["red-cup"],
      scent: ["none"],
      lobes: ["none"],
      site: ["forest", "open", "street"],
    },
  },
  {
    id: "araucaria-heterophylla",
    scientificName: "Araucaria heterophylla",
    commonNames: ["Norfolk Island pine"],
    family: "Araucariaceae",
    nativeRegions: ["pacific-islands"],
    plantedRegions: ["oceania", "africa", "south-america", "north-america", "europe", "southeast-asia"],
    rangeText: "Native to Norfolk Island. Planted on warm coasts worldwide as an ornamental.",
    summary:
      "A formal conifer with whorled, horizontal tiers of branches. Leaves are short awls, not pine needles in bundles. Female cones are large and woody. A tiered crown in the tropics is often Araucaria columnaris, which is not on this sheet. Do not assume Norfolk Island pine from the crown alone.",
    traits: ["Tiered branches", "Awl leaves", "Not a true pine"],
    woodyNote: "Branches come off the trunk in regular whorls.",
    similarTo: ["araucaria-cunninghamii", "pinus-radiata"],
    characters: {
      habit: ["tree"],
      arrangement: ["whorled"],
      leafType: ["scale-like"],
      shape: ["linear"],
      margin: ["entire"],
      bark: ["scaly"],
      exudate: ["resin"],
      reproductive: ["cone"],
      fruit: ["cone"],
      scent: ["aromatic"],
      site: ["coast", "street", "open"],
    },
  },
  {
    id: "araucaria-cunninghamii",
    scientificName: "Araucaria cunninghamii",
    commonNames: ["hoop pine"],
    family: "Araucariaceae",
    nativeRegions: ["oceania", "pacific-islands"],
    plantedRegions: ["southeast-asia"],
    rangeText: "Native to eastern Australian rainforests and New Guinea, including highland forests.",
    summary:
      "A New Guinea and Queensland rainforest emergent. Bark is rough, with horizontal hoops. It does not have the tidy tiered crown of a Norfolk Island pine.",
    traits: ["Hooped bark", "Rainforest crown", "Not Norfolk Island pine"],
    woodyNote: "Bark hoops are the field mark on a large trunk.",
    similarTo: ["araucaria-heterophylla", "nothofagus-grandis"],
    characters: {
      habit: ["tree"],
      leafType: ["scale-like", "needle"],
      shape: ["linear"],
      margin: ["entire"],
      bark: ["fissured"],
      exudate: ["resin"],
      reproductive: ["cone"],
      fruit: ["cone"],
      scent: ["aromatic"],
      site: ["forest"],
    },
  },
  {
    id: "eucalyptus-globulus",
    scientificName: "Eucalyptus globulus",
    commonNames: ["Tasmanian blue gum"],
    family: "Myrtaceae",
    nativeRegions: ["oceania"],
    plantedRegions: ["europe", "africa", "south-america", "north-america", "south-asia", "southeast-asia", "east-asia", "pacific-islands"],
    rangeText: "Native to Tasmania and southern Victoria. Planted for timber and ornament on other continents.",
    summary:
      "Adult leaves are long, alternate, entire and hang vertically. They smell strongly when crushed. Bark sheds in ribbons. The fruit is a woody capsule.",
    traits: ["Hanging lanceolate leaves", "Strong smell", "Shedding bark", "Woody gum nuts"],
    woodyNote: "Juvenile leaves are opposite and rounder than the adult leaves. A broken twig smells of aromatic oil, not white latex.",
    invasive:
      "Invasive in parts of California, Chile and South Africa. Do not plant it outside its range on a hunch.",
    similarTo: ["cinnamomum-camphora"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate", "opposite"],
      leafType: ["simple"],
      shape: ["lanceolate"],
      margin: ["entire"],
      venation: ["pinnate"],
      texture: ["glossy"],
      petiole: ["long"],
      lobes: ["none"],
      bark: ["peeling"],
      exudate: ["none"],
      reproductive: ["showy"],
      fruit: ["woody-capsule"],
      scent: ["aromatic"],
      site: ["forest", "open", "street"],
    },
  },
  {
    id: "ailanthus-altissima",
    scientificName: "Ailanthus altissima",
    commonNames: ["tree of heaven"],
    family: "Simaroubaceae",
    nativeRegions: ["east-asia"],
    plantedRegions: ["europe", "north-america", "oceania", "west-asia", "south-asia", "africa", "south-america"],
    rangeText: "Native to China. Now a street and wasteland tree on several continents.",
    summary:
      "Large pinnate leaves. Each leaflet has one or two glandular teeth at the base. A crushed leaf smells foul. Fruits are twisted winged keys.",
    traits: ["Pinnate leaves", "Glandular teeth", "Foul smell", "Twisted samaras"],
    invasive: "A serious urban invader. Do not move soil or suckers from it.",
    similarTo: ["jacaranda-mimosifolia", "mangifera-indica"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["pinnate"],
      shape: ["lanceolate"],
      margin: ["toothed"],
      venation: ["pinnate"],
      texture: ["smooth"],
      petiole: ["long"],
      lobes: ["none"],
      bark: ["smooth"],
      exudate: ["none"],
      buds: ["small-dry"],
      reproductive: ["tiny"],
      fruit: ["samara"],
      scent: ["foul"],
      site: ["street", "open"],
    },
  },
  {
    id: "ficus-carica",
    scientificName: "Ficus carica",
    commonNames: ["common fig"],
    family: "Moraceae",
    nativeRegions: ["europe", "west-asia", "africa"],
    plantedRegions: ["north-america", "south-america", "oceania", "south-asia", "east-asia"],
    rangeText: "Native to the Mediterranean and western Asia. Grown in warm gardens far outside that range.",
    summary:
      "Often a shrub-tree with rough, lobed leaves and white latex from a torn leaf. The fruit is a fig. Some shoots carry unlobed leaves.",
    traits: ["Rough lobed leaves", "White latex", "Figs"],
    similarTo: ["ficus-benjamina", "ricinus-communis"],
    characters: {
      habit: ["tree", "shrub"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lobed-palmate", "elliptic"],
      margin: ["entire"],
      venation: ["palmate"],
      texture: ["rough"],
      petiole: ["long"],
      lobes: ["five", "three", "none"],
      bark: ["smooth"],
      exudate: ["white-latex"],
      reproductive: ["fig"],
      fruit: ["fig"],
      scent: ["none"],
      site: ["open", "street"],
    },
  },
  {
    id: "ficus-benjamina",
    scientificName: "Ficus benjamina",
    commonNames: ["weeping fig"],
    family: "Moraceae",
    nativeRegions: ["south-asia", "southeast-asia", "oceania", "pacific-islands"],
    plantedRegions: ["africa", "south-america", "north-america", "east-asia"],
    rangeText: "Native from India through Southeast Asia into northern Australia. A street tree and a house plant.",
    summary:
      "Glossy entire leaves with a drip tip, on a weeping crown. A torn leaf bleeds white latex. Fruits are small figs.",
    traits: ["Glossy drip-tip leaves", "White latex", "Small figs"],
    similarTo: ["ficus-carica", "mangifera-indica"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["elliptic"],
      margin: ["entire"],
      venation: ["pinnate"],
      texture: ["glossy"],
      petiole: ["short"],
      lobes: ["none"],
      bark: ["smooth"],
      exudate: ["white-latex"],
      reproductive: ["fig"],
      fruit: ["fig"],
      scent: ["none"],
      site: ["street", "indoor", "open"],
    },
  },
  {
    id: "mangifera-indica",
    scientificName: "Mangifera indica",
    commonNames: ["mango"],
    family: "Anacardiaceae",
    nativeRegions: ["south-asia"],
    plantedRegions: ["southeast-asia", "east-asia", "africa", "south-america", "central-america", "pacific-islands", "oceania", "north-america"],
    rangeText: "Native to tropical South Asia. Planted throughout the tropics.",
    summary:
      "Simple lanceolate leaves crowded near the twig tips, often glossy, with a resinous smell. A broken twig can bleed milky sap. The fruit is a large drupe.",
    traits: ["Lanceolate leaves in flushes", "Milky sap", "Large drupe"],
    toxic: "Mango sap can blister the skin. Do not cut the bark to see it.",
    similarTo: ["cinnamomum-camphora", "ficus-benjamina"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lanceolate"],
      margin: ["entire"],
      venation: ["pinnate"],
      texture: ["glossy"],
      petiole: ["long"],
      lobes: ["none"],
      bark: ["fissured"],
      exudate: ["white-latex"],
      reproductive: ["tiny"],
      fruit: ["drupe"],
      scent: ["aromatic"],
      site: ["open", "street"],
    },
  },
  {
    id: "olea-europaea",
    scientificName: "Olea europaea",
    commonNames: ["olive"],
    family: "Oleaceae",
    nativeRegions: ["europe", "africa", "west-asia"],
    plantedRegions: ["north-america", "south-america", "oceania", "south-asia"],
    rangeText: "Native to the Mediterranean basin. Grown in other winter-rain climates.",
    summary:
      "Opposite, narrow, gray-green leaves with the edge rolled under. Bark is gray and furrowed. The fruit is a drupe.",
    traits: ["Opposite gray leaves", "Rolled margin", "Furrowed trunk"],
    similarTo: ["nerium-oleander"],
    characters: {
      habit: ["tree"],
      arrangement: ["opposite"],
      leafType: ["simple"],
      shape: ["lanceolate"],
      margin: ["rolled-under", "entire"],
      venation: ["pinnate"],
      texture: ["smooth"],
      petiole: ["short"],
      lobes: ["none"],
      bark: ["fissured"],
      exudate: ["none"],
      reproductive: ["tiny"],
      fruit: ["drupe"],
      scent: ["none"],
      site: ["open", "street"],
    },
  },
  {
    id: "jacaranda-mimosifolia",
    scientificName: "Jacaranda mimosifolia",
    commonNames: ["jacaranda"],
    family: "Bignoniaceae",
    nativeRegions: ["south-america"],
    plantedRegions: ["africa", "oceania", "north-america", "central-america", "south-asia", "southeast-asia", "europe", "east-asia"],
    rangeText: "Native to northwestern Argentina and southern Bolivia. A street tree in warm cities worldwide.",
    summary:
      "Opposite, twice-pinnate ferny leaves and clusters of purple flowers. The fruit is a round, flat woody pod.",
    traits: ["Opposite bipinnate leaves", "Purple flowers", "Flat round pods"],
    similarTo: ["delonix-regia", "ailanthus-altissima"],
    characters: {
      habit: ["tree"],
      arrangement: ["opposite"],
      leafType: ["bipinnate"],
      shape: ["lanceolate"],
      margin: ["entire"],
      texture: ["smooth"],
      lobes: ["none"],
      bark: ["fissured"],
      exudate: ["none"],
      reproductive: ["showy"],
      fruit: ["pod"],
      scent: ["none"],
      site: ["street", "open"],
    },
  },
  {
    id: "delonix-regia",
    scientificName: "Delonix regia",
    commonNames: ["flamboyant", "royal poinciana"],
    family: "Fabaceae",
    nativeRegions: ["africa"],
    plantedRegions: ["south-asia", "southeast-asia", "pacific-islands", "central-america", "south-america", "north-america", "oceania"],
    rangeText: "Native to Madagascar. Planted through the tropics as a shade tree.",
    summary:
      "A wide, flat-crowned tree with alternate bipinnate leaves and large red flowers. Pods are very long and flat.",
    traits: ["Alternate bipinnate leaves", "Red flowers", "Very long pods"],
    similarTo: ["jacaranda-mimosifolia"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["bipinnate"],
      shape: ["lanceolate"],
      margin: ["entire"],
      texture: ["smooth"],
      lobes: ["none"],
      bark: ["smooth"],
      exudate: ["none"],
      reproductive: ["showy"],
      fruit: ["pod"],
      scent: ["none"],
      site: ["street", "open"],
    },
  },
  {
    id: "adansonia-digitata",
    scientificName: "Adansonia digitata",
    commonNames: ["baobab"],
    family: "Malvaceae",
    nativeRegions: ["africa"],
    plantedRegions: [],
    rangeText: "Native to the dry savannas of Africa. Rarely grown far outside that range.",
    summary:
      "A massive smooth trunk and palmately compound leaves. Flowers hang. The fruit is a large woody oval. A hit outside Africa needs a specialist, because this sheet has no lookalikes from other dry regions.",
    traits: ["Huge smooth trunk", "Palmate compound leaves", "Large woody fruit"],
    woodyNote: "The trunk stores water. Bark is smooth and pale.",
    similarTo: [],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["palmate-compound"],
      shape: ["elliptic"],
      margin: ["entire"],
      texture: ["smooth"],
      lobes: ["none"],
      bark: ["smooth"],
      exudate: ["none"],
      reproductive: ["showy"],
      fruit: ["large-nut"],
      scent: ["none"],
      site: ["open"],
    },
  },
  {
    id: "cocos-nucifera",
    scientificName: "Cocos nucifera",
    commonNames: ["coconut"],
    family: "Arecaceae",
    nativeRegions: ["pacific-islands", "southeast-asia"],
    plantedRegions: ["south-asia", "africa", "south-america", "central-america", "oceania", "east-asia"],
    rangeText: "A coastal palm of the tropical Indian and Pacific oceans. Planted on tropical shores worldwide.",
    summary:
      "A single-trunk palm with long pinnate fronds and a large fibrous fruit. A tree of beaches, not of highland forest.",
    traits: ["Pinnate crown", "Coastal", "Large fibrous fruit"],
    similarTo: ["phoenix-dactylifera"],
    characters: {
      habit: ["palm", "tree"],
      leafType: ["pinnate"],
      shape: ["linear"],
      margin: ["entire"],
      venation: ["parallel"],
      bark: ["smooth"],
      reproductive: ["spadix"],
      fruit: ["large-nut"],
      scent: ["none"],
      site: ["coast", "open"],
    },
  },
  {
    id: "phoenix-dactylifera",
    scientificName: "Phoenix dactylifera",
    commonNames: ["date palm"],
    family: "Arecaceae",
    nativeRegions: ["africa", "west-asia"],
    plantedRegions: ["south-asia", "europe", "north-america", "oceania"],
    rangeText: "Native to North Africa and western Asia. Planted in other hot, dry districts.",
    summary:
      "A pinnate palm of dry places. The lower leaflets are stiff spines. Fruit is a date, not a coconut.",
    traits: ["Pinnate crown", "Spiny leaf base", "Dates", "Dry sites"],
    similarTo: ["cocos-nucifera"],
    characters: {
      habit: ["palm", "tree"],
      leafType: ["pinnate"],
      shape: ["linear"],
      margin: ["spiny"],
      venation: ["parallel"],
      bark: ["scaly"],
      reproductive: ["spadix"],
      fruit: ["date"],
      scent: ["none"],
      site: ["open", "street"],
    },
  },
  {
    id: "salix-babylonica",
    scientificName: "Salix babylonica",
    commonNames: ["weeping willow"],
    family: "Salicaceae",
    nativeRegions: ["east-asia"],
    plantedRegions: ["europe", "north-america", "oceania", "south-america", "west-asia", "south-asia"],
    rangeText: "Native to China. Planted beside water in temperate countries.",
    summary:
      "Long hanging shoots and narrow, finely toothed leaves. Catkins appear with the leaves. Almost always near water or a lawn pond. Most weeping willows in parks are hybrids, often Salix × sepulcralis. This sheet has only this name, so a hit is the weeping look, not a finished determination.",
    traits: ["Weeping shoots", "Narrow toothed leaves", "Waterside"],
    woodyNote: "The hanging shoot is the architecture mark. Buds are small and pressed to the twig.",
    similarTo: ["populus-tremuloides"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lanceolate"],
      margin: ["toothed"],
      venation: ["pinnate"],
      texture: ["smooth"],
      petiole: ["short"],
      lobes: ["none"],
      bark: ["fissured"],
      exudate: ["none"],
      buds: ["small-dry"],
      reproductive: ["catkin"],
      scent: ["none"],
      site: ["wetland", "open", "street"],
    },
  },
  {
    id: "populus-tremuloides",
    scientificName: "Populus tremuloides",
    commonNames: ["quaking aspen"],
    family: "Salicaceae",
    nativeRegions: ["north-america"],
    plantedRegions: ["europe"],
    rangeText: "Native across much of North America, including high mountains.",
    summary:
      "Small roundish leaves on a flattened petiole, so they tremble. Bark is pale and smooth, with black scars. Buds are resinous.",
    traits: ["Flattened petiole", "Pale smooth bark", "Resinous buds"],
    woodyNote: "Winter buds are sticky. The trunk stays smooth until it is old.",
    similarTo: ["betula-pendula", "salix-babylonica"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["ovate"],
      margin: ["toothed"],
      venation: ["pinnate"],
      texture: ["smooth"],
      petiole: ["flattened"],
      lobes: ["none"],
      bark: ["smooth"],
      exudate: ["none"],
      buds: ["resinous"],
      reproductive: ["catkin"],
      fruit: ["fluff-capsule"],
      scent: ["none"],
      site: ["forest", "open"],
    },
  },
  {
    id: "cinnamomum-camphora",
    scientificName: "Cinnamomum camphora",
    commonNames: ["camphor tree"],
    family: "Lauraceae",
    nativeRegions: ["east-asia"],
    plantedRegions: ["oceania", "north-america", "africa", "south-asia", "southeast-asia"],
    rangeText: "Native to East Asia, including Taiwan, China and Japan. Planted in warm cities.",
    summary:
      "Glossy entire leaves with three main veins from the base. A crushed leaf smells of camphor. Fruits are small black drupes.",
    traits: ["Three basal veins", "Camphor smell", "Glossy entire leaves"],
    invasive: "Invasive in parts of eastern Australia and the southeastern United States.",
    similarTo: ["mangifera-indica", "eucalyptus-globulus"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["elliptic"],
      margin: ["entire"],
      venation: ["palmate"],
      texture: ["glossy"],
      petiole: ["long"],
      lobes: ["none"],
      bark: ["fissured"],
      exudate: ["none"],
      reproductive: ["tiny"],
      fruit: ["drupe"],
      scent: ["aromatic"],
      site: ["street", "forest", "open"],
    },
  },
  {
    id: "casuarina-equisetifolia",
    scientificName: "Casuarina equisetifolia",
    commonNames: ["beach she-oak", "Australian pine"],
    family: "Casuarinaceae",
    nativeRegions: ["southeast-asia", "oceania", "pacific-islands", "south-asia"],
    plantedRegions: ["africa", "central-america", "north-america"],
    rangeText: "Native to tropical coasts from Southeast Asia through Australia and the Pacific.",
    summary:
      "Looks like a pine from a distance and is not one. The green 'needles' are jointed branchlets with tiny whorled scales. Fruit is a small woody cone-like body.",
    traits: ["Jointed green branchlets", "Not a pine", "Cone-like fruit", "Sandy coasts"],
    woodyNote: "Photosynthesis is on the branchlets. True leaves are minute scales.",
    invasive: "Can take over sandy coasts outside its range.",
    similarTo: ["pinus-sylvestris"],
    characters: {
      habit: ["tree"],
      arrangement: ["whorled"],
      leafType: ["scale-like"],
      shape: ["linear"],
      margin: ["entire"],
      bark: ["fissured"],
      exudate: ["none"],
      reproductive: ["cone"],
      fruit: ["cone-like"],
      scent: ["none"],
      site: ["coast", "open"],
    },
  },
  {
    id: "rhizophora-mangle",
    scientificName: "Rhizophora mangle",
    commonNames: ["red mangrove"],
    family: "Rhizophoraceae",
    nativeRegions: ["africa", "south-america", "central-america", "north-america"],
    plantedRegions: [],
    rangeText: "Coasts of the tropical Atlantic and the eastern Pacific.",
    summary:
      "A mangrove with arching prop roots and opposite, entire, elliptic leaves. Seedlings germinate on the tree and hang as long green propagules.",
    traits: ["Prop roots", "Opposite entire leaves", "Hanging seedlings"],
    woodyNote: "Do not dig the prop roots. They hold the tree in mud.",
    similarTo: ["kandelia-obovata"],
    characters: {
      habit: ["tree", "shrub"],
      arrangement: ["opposite"],
      leafType: ["simple"],
      shape: ["elliptic"],
      margin: ["entire"],
      venation: ["pinnate"],
      texture: ["glossy"],
      petiole: ["short"],
      lobes: ["none"],
      bark: ["smooth"],
      exudate: ["none"],
      roots: ["prop"],
      reproductive: ["tiny"],
      fruit: ["propagule"],
      scent: ["none"],
      site: ["coast", "wetland"],
    },
  },
  {
    id: "kandelia-obovata",
    scientificName: "Kandelia obovata",
    commonNames: ["kandelia"],
    family: "Rhizophoraceae",
    nativeRegions: ["east-asia"],
    plantedRegions: ["southeast-asia"],
    rangeText: "Coasts of Taiwan, southern China, Japan and northern Vietnam.",
    summary:
      "The common mangrove of Taiwan and nearby coasts. Opposite, entire, obovate leaves and hanging seedlings. It does not build the long prop-root stilts of red mangrove. Other mangroves with an obovate leaf are not on this sheet.",
    traits: ["Opposite obovate leaves", "Hanging seedlings", "Short roots, not long stilts"],
    woodyNote: "A Taiwan wetland and estuary tree. Leave the pneumatophores and seedlings in place.",
    similarTo: ["rhizophora-mangle"],
    characters: {
      habit: ["tree", "shrub"],
      arrangement: ["opposite"],
      leafType: ["simple"],
      shape: ["elliptic", "obovate"],
      margin: ["entire"],
      venation: ["pinnate"],
      texture: ["glossy"],
      petiole: ["short"],
      lobes: ["none"],
      bark: ["smooth"],
      exudate: ["none"],
      roots: ["none"],
      reproductive: ["tiny"],
      fruit: ["propagule"],
      scent: ["none"],
      site: ["coast", "wetland"],
    },
  },
  {
    id: "nothofagus-grandis",
    scientificName: "Nothofagus grandis",
    commonNames: ["New Guinea beech"],
    family: "Nothofagaceae",
    nativeRegions: ["pacific-islands"],
    plantedRegions: [],
    rangeText: "Montane forests of New Guinea.",
    summary:
      "A highland New Guinea tree with large simple leaves and many straight side veins. This sheet has only one New Guinea beech, so a similar highland tree can land here by mistake.",
    traits: ["Large simple leaves", "Many straight side veins", "Highland forest"],
    woodyNote: "Treat a hit as a prompt to open a local flora, not as a finished name.",
    similarTo: ["fagus-sylvatica", "araucaria-cunninghamii"],
    characters: {
      habit: ["tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["elliptic", "ovate"],
      margin: ["toothed", "wavy"],
      venation: ["pinnate"],
      texture: ["smooth"],
      petiole: ["short"],
      lobes: ["none"],
      bark: ["scaly"],
      exudate: ["none"],
      buds: ["small-dry"],
      fruit: ["nut-in-husk"],
      scent: ["none"],
      site: ["forest"],
    },
  },
  {
    id: "taraxacum-officinale",
    scientificName: "Taraxacum officinale",
    nameKind: "aggregate",
    commonNames: ["dandelion"],
    family: "Asteraceae",
    nativeRegions: ["europe", "west-asia"],
    plantedRegions: elsewhere(["europe", "west-asia"]),
    rangeText: "Native to Eurasia. Naturalized in lawns on every continent except Antarctica.",
    summary:
      "The dandelion aggregate. A basal rosette of pinnately lobed leaves with white latex. One yellow flower head sits on a hollow stalk, then a fluffy seed head. This sheet does not separate microspecies.",
    traits: ["Basal lobed leaves", "White latex", "One flower head", "Fluffy seeds"],
    similarTo: ["plantago-major"],
    characters: {
      habit: ["herb"],
      arrangement: ["basal"],
      leafType: ["simple"],
      shape: ["lobed-pinnate"],
      margin: ["toothed"],
      venation: ["pinnate"],
      texture: ["smooth"],
      lobes: ["many"],
      exudate: ["white-latex"],
      reproductive: ["flower-head"],
      fruit: ["pappus"],
      scent: ["none"],
      site: ["lawn", "open"],
    },
  },
  {
    id: "plantago-major",
    scientificName: "Plantago major",
    commonNames: ["broadleaf plantain"],
    family: "Plantaginaceae",
    nativeRegions: ["europe", "west-asia"],
    plantedRegions: elsewhere(["europe", "west-asia"]),
    rangeText: "Native to Eurasia. A lawn and path weed worldwide.",
    summary:
      "A basal rosette of broad elliptic leaves with veins that look parallel. Flowers are a narrow green spike. No white latex.",
    traits: ["Basal elliptic leaves", "Strong parallel-looking veins", "Green spike"],
    similarTo: ["taraxacum-officinale"],
    characters: {
      habit: ["herb"],
      arrangement: ["basal"],
      leafType: ["simple"],
      shape: ["elliptic"],
      margin: ["entire"],
      venation: ["parallel"],
      texture: ["smooth"],
      lobes: ["none"],
      exudate: ["none"],
      reproductive: ["tiny"],
      fruit: ["capsule"],
      scent: ["none"],
      site: ["lawn", "open"],
    },
  },
  {
    id: "trifolium-repens",
    scientificName: "Trifolium repens",
    commonNames: ["white clover"],
    family: "Fabaceae",
    nativeRegions: ["europe", "west-asia", "africa"],
    plantedRegions: elsewhere(["europe", "west-asia", "africa"]),
    rangeText: "Native to Europe and the Mediterranean. Sown and naturalized in lawns worldwide.",
    summary:
      "A creeping herb with leaves of three leaflets and white flower heads. It roots along the stem.",
    traits: ["Three leaflets", "White flower heads", "Creeping stems"],
    similarTo: ["taraxacum-officinale"],
    characters: {
      habit: ["herb"],
      arrangement: ["alternate"],
      leafType: ["palmate-compound"],
      shape: ["ovate"],
      margin: ["toothed"],
      venation: ["pinnate"],
      texture: ["smooth"],
      lobes: ["none"],
      exudate: ["none"],
      reproductive: ["flower-head"],
      fruit: ["pod"],
      scent: ["none"],
      site: ["lawn", "open"],
    },
  },
  {
    id: "nerium-oleander",
    scientificName: "Nerium oleander",
    commonNames: ["oleander"],
    family: "Apocynaceae",
    nativeRegions: ["europe", "africa", "west-asia"],
    plantedRegions: elsewhere(["europe", "africa", "west-asia"]),
    rangeText: "Native to the Mediterranean and nearby. Planted as a shrub in warm cities worldwide.",
    summary:
      "A shrub with narrow entire leaves in whorls or opposite pairs, and showy pink, white or red flowers. A broken leaf bleeds white latex.",
    traits: ["Whorled narrow leaves", "Showy flowers", "White latex"],
    toxic:
      "Oleander is poisonous in every part, including smoke from burning it and water that held the stems. Do not taste it.",
    similarTo: ["olea-europaea"],
    characters: {
      habit: ["shrub"],
      arrangement: ["whorled", "opposite"],
      leafType: ["simple"],
      shape: ["lanceolate"],
      margin: ["entire"],
      venation: ["pinnate"],
      texture: ["smooth"],
      petiole: ["short"],
      lobes: ["none"],
      bark: ["smooth"],
      exudate: ["white-latex"],
      reproductive: ["showy"],
      fruit: ["pod"],
      scent: ["none"],
      site: ["street", "open"],
    },
  },
  {
    id: "lantana-camara",
    scientificName: "Lantana camara",
    commonNames: ["lantana"],
    family: "Verbenaceae",
    nativeRegions: ["central-america", "south-america"],
    plantedRegions: ["africa", "south-asia", "southeast-asia", "oceania", "pacific-islands", "east-asia", "north-america"],
    rangeText: "Native to tropical America. A thicket weed through the warm parts of the world.",
    summary:
      "A rough shrub with opposite toothed leaves and heads of small flowers that change color. Fruits are small dark drupes. Crushed leaves smell strong.",
    traits: ["Opposite rough leaves", "Multicolor flower heads", "Strong smell"],
    invasive: "A thicket-forming weed in warm countries. Do not carry cuttings.",
    toxic: "The fruit is poisonous, especially when unripe. Do not eat the berries.",
    similarTo: ["nerium-oleander"],
    characters: {
      habit: ["shrub"],
      arrangement: ["opposite"],
      leafType: ["simple"],
      shape: ["ovate"],
      margin: ["toothed"],
      venation: ["pinnate"],
      texture: ["rough"],
      petiole: ["short"],
      lobes: ["none"],
      exudate: ["none"],
      reproductive: ["flower-head"],
      fruit: ["drupe"],
      scent: ["aromatic"],
      site: ["open", "forest"],
    },
  },
  {
    id: "hedera-helix",
    scientificName: "Hedera helix",
    commonNames: ["English ivy"],
    family: "Araliaceae",
    nativeRegions: ["europe"],
    plantedRegions: ["north-america", "oceania", "east-asia", "west-asia"],
    rangeText: "Native to Europe. Planted and escaped on other temperate continents.",
    summary:
      "A climbing vine. Juvenile leaves are glossy and palmately lobed. Adult leaves on flowering shoots are unlobed. Fruits are black berries.",
    traits: ["Climbing vine", "Lobed juvenile leaves", "Glossy surface"],
    invasive: "Climbs and smothers trees outside European woods. Cut it off trunks rather than planting more.",
    similarTo: [],
    characters: {
      habit: ["vine"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lobed-palmate", "elliptic"],
      margin: ["entire"],
      venation: ["palmate"],
      texture: ["glossy"],
      petiole: ["long"],
      lobes: ["five", "none"],
      exudate: ["none"],
      reproductive: ["tiny"],
      fruit: ["berry"],
      scent: ["none"],
      site: ["forest", "street"],
    },
  },
  {
    id: "musa-acuminata",
    scientificName: "Musa acuminata",
    commonNames: ["banana"],
    family: "Musaceae",
    nativeRegions: ["southeast-asia", "south-asia", "pacific-islands"],
    plantedRegions: ["africa", "central-america", "south-america", "east-asia", "oceania", "north-america"],
    rangeText: "Native to tropical Asia and New Guinea. Grown through the tropics.",
    summary:
      "A giant herb, not a woody tree. The 'trunk' is wrapped leaf bases. Leaves are huge, with a thick midrib and parallel veins. The flower spike hangs. Bananas in markets and gardens are mostly hybrids. This sheet does not separate cultivars.",
    traits: ["Trunk of leaf bases", "Huge parallel-veined leaves", "Hanging spike"],
    similarTo: [],
    characters: {
      habit: ["herb", "tree"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["elliptic"],
      margin: ["entire"],
      venation: ["parallel"],
      texture: ["glossy"],
      petiole: ["long"],
      lobes: ["none"],
      exudate: ["none"],
      reproductive: ["spadix"],
      fruit: ["banana"],
      scent: ["none"],
      site: ["open", "street"],
    },
  },
  {
    id: "opuntia-ficus-indica",
    scientificName: "Opuntia ficus-indica",
    commonNames: ["prickly pear"],
    family: "Cactaceae",
    nativeRegions: ["north-america", "central-america"],
    plantedRegions: ["africa", "europe", "oceania", "south-america", "west-asia", "south-asia"],
    rangeText: "Native to Mexico. Planted in dry districts worldwide.",
    summary:
      "Flat green pads with spines or clusters of tiny barbed bristles. Flowers are showy. The fruit is fleshy and sits on the pad.",
    traits: ["Flat pads", "Spines or glochids", "Fleshy fruit on the pad"],
    invasive:
      "Invasive in parts of Australia, South Africa and the Mediterranean. Pads root where they fall.",
    similarTo: [],
    characters: {
      habit: ["succulent", "shrub"],
      shape: ["pad"],
      margin: ["spiny"],
      texture: ["smooth"],
      reproductive: ["showy"],
      fruit: ["tuna"],
      scent: ["none"],
      site: ["open"],
    },
  },
  {
    id: "pteridium-aquilinum",
    scientificName: "Pteridium aquilinum",
    commonNames: ["bracken"],
    family: "Dennstaedtiaceae",
    nativeRegions: ALL_REGIONS,
    plantedRegions: [],
    rangeText: "A cosmopolitan fern of open woods and hillsides.",
    summary:
      "A large divided frond from an underground rhizome. Not a flowering plant, so there is no flower or fleshy fruit. New fronds uncoil.",
    traits: ["Large divided frond", "No flower", "Fronds from a rhizome"],
    toxic: "Bracken is poisonous to livestock, and the fronds carry a carcinogen. Do not eat the fiddleheads from this result.",
    similarTo: [],
    characters: {
      habit: ["fern"],
      arrangement: ["basal"],
      leafType: ["frond"],
      shape: ["lobed-pinnate"],
      margin: ["toothed"],
      venation: ["pinnate"],
      texture: ["smooth"],
      lobes: ["many"],
      scent: ["none"],
      site: ["forest", "open"],
    },
  },
  {
    id: "phyllostachys-edulis",
    scientificName: "Phyllostachys edulis",
    commonNames: ["moso bamboo"],
    family: "Poaceae",
    nativeRegions: ["east-asia"],
    plantedRegions: ["europe", "north-america", "oceania", "south-asia"],
    rangeText: "Native to China and Taiwan. Planted in temperate gardens.",
    summary:
      "A woody grass. Culms are hollow, jointed and smooth. Leaves are narrow with parallel veins, on branches at the nodes. It is not a pine.",
    traits: ["Jointed woody culms", "Narrow parallel-veined leaves", "Not a conifer"],
    woodyNote: "Branches come off at the nodes. The culm is the trunk.",
    similarTo: ["casuarina-equisetifolia"],
    characters: {
      habit: ["grass", "tree", "shrub"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lanceolate"],
      margin: ["entire"],
      venation: ["parallel"],
      texture: ["smooth"],
      lobes: ["none"],
      bark: ["smooth"],
      exudate: ["none"],
      scent: ["none"],
      site: ["forest", "open", "street"],
    },
  },
  {
    id: "ricinus-communis",
    scientificName: "Ricinus communis",
    commonNames: ["castor"],
    family: "Euphorbiaceae",
    nativeRegions: ["africa"],
    plantedRegions: elsewhere(["africa"]),
    rangeText: "Native to northeastern Africa. A pantropical weed and an ornamental.",
    summary:
      "Large palmately lobed leaves on a reddish stem, often shrubby. The fruit is a spiny capsule. Seeds are the dangerous part.",
    traits: ["Large palmate lobes", "Spiny capsules", "Often red stems"],
    toxic: "Castor seeds are dangerously poisonous. Do not crack them open or taste them.",
    similarTo: ["ficus-carica"],
    characters: {
      habit: ["shrub", "herb"],
      arrangement: ["alternate"],
      leafType: ["simple"],
      shape: ["lobed-palmate"],
      margin: ["toothed"],
      venation: ["palmate"],
      texture: ["glossy"],
      petiole: ["long"],
      lobes: ["many"],
      exudate: ["none"],
      reproductive: ["tiny"],
      fruit: ["spiny-capsule"],
      scent: ["none"],
      site: ["open", "street"],
    },
  },
  {
    id: "pontederia-crassipes",
    scientificName: "Pontederia crassipes",
    commonNames: ["water hyacinth"],
    family: "Pontederiaceae",
    nativeRegions: ["south-america"],
    plantedRegions: ["africa", "south-asia", "southeast-asia", "east-asia", "north-america", "central-america", "oceania", "pacific-islands"],
    rangeText: "Native to tropical South America. A floating weed of warm still water worldwide. Older books call it Eichhornia crassipes.",
    summary:
      "A floating herb with inflated leaf stalks, glossy heart-shaped leaves, and a spike of lilac flowers. It forms mats on still water.",
    traits: ["Inflated petioles", "Heart-shaped leaves", "Lilac spike", "Floating mat"],
    invasive: "Blocks waterways. Do not tip it into a pond or a river.",
    similarTo: [],
    characters: {
      habit: ["herb"],
      arrangement: ["basal"],
      leafType: ["simple"],
      shape: ["cordate"],
      margin: ["entire"],
      venation: ["parallel"],
      texture: ["glossy"],
      petiole: ["winged"],
      lobes: ["none"],
      exudate: ["none"],
      reproductive: ["showy"],
      fruit: ["capsule"],
      scent: ["none"],
      site: ["wetland"],
    },
  },
]

const BY_ID = new Map(TAXA.map((taxon) => [taxon.id, taxon]))

export function taxonById(id: string): Taxon | undefined {
  return BY_ID.get(id)
}

export function displayName(taxon: Pick<Taxon, "scientificName" | "nameKind">): string {
  switch (taxon.nameKind) {
    case "aggregate":
      return `${taxon.scientificName} agg.`
    case "hybrid":
    case "species":
    case undefined:
      return taxon.scientificName
    default: {
      const exhaustive: never = taxon.nameKind
      return exhaustive
    }
  }
}
